### ISSUE TITLE
Update SDK to File API v2

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-java#24]
Smartling File API v2 will be released soon. SDK should be ready for this release.

**DoD**: 
* Cover in SDK mandatory methods:
 * File Status (for locale)
 * File Status (for all locales)
 * Last modified (for locale)
 * Last modified (for all locales)
 * Authorize Locales
 * Un-authorize Locales
* Each subtask above includes:
 * Unit tests
 * Integration test
* Implemented new authentication flow via API gateway
 * OAuth flow
 * Caching `refresh_token` and `access_token`
 * Request new token in case of expiration or 401
* `/example/SmartlingApiExample.java` is updated
* New version is published in Maven repository

**Comment by dimitrystd** [comment]
#### Current implementation
It looks like
![](http://www.plantuml.com:80/plantuml/png/hLH1Ri8m4Bpd5Jw64lX0AoHeYzH3ArJA0qoo2QuSEtAS5bJrxrqx8TX9e1KgXqGxE-pEUZQEEIrBiiwfqfo9R5wmPofe1efy1OHCvfNU8NRF6GXDg1lTcloISJZbKpSo-UaK7-EXwk5QAqH8LO9wIYBYX6k85UWMAfHyXrWR4XR3NuDlQGcDl8tYaGitgX0UjI8s1PSqCPa7gYcfsZ0q3olzJTQajbQyeweqKkh6XbWpLbJH73IeHSLuWkDiwxTfD_wGB249SCpR-aqnqs6Zs8cYG60HboAvLOIiLeA0p-NnZzz145kxV5UCKUDNA0ifIhWpEKHPJ3MJubuA3NizizOrC8HTJfvJaRYK4tgSVQNa_e3LKfPLoXACCHqe6lR6KUxlYw_STsZcMZGuL4-mHLspBhhwWeSV_MfiUZOL4UmeS3FhtdWA9BQlaJVLOrxemp6QkNjnnL3-Absdm5cxVr3GMzCBejejw37C8dJ1C6M2yhykNaqUl0CwoVO-ETqD0pqoq7qqj0VRr476mklJpQwEZK8xUZ1q3TvC9lxNV9RbVJa_)
How to use:
```java
SmartlingApiManager fileApi = new SmartlingApiManager(userId, userSecret, projectId, baseAuthApiUrl, String baseFileApiUrl);
fileApi.deleteFile(fileUri);
```
#### Proposed implementation
The first step in using the SDK is always authenticating and connecting to the API. Doesn't matter which API you are going to use (Files\Projects\Jobs), you must authenticate and get `access_token`. It is responsible for things such as:
* Storing authentication information
* Automatically refreshing tokens

You can also create more than one `SmartlingAuthApi`. For example, you can have a connection for each user if your application supports multiple user accounts.
![](http://www.plantuml.com:80/plantuml/png/hLJRJiCm37tVL-InOzr-WAaI6qpY0JGnzW6cTKTGcbHfoaM8VyT9koxfoa0JUsZbupFxECTDAg2gsAO0RGINkwkItu647MesdxCSKiYG9Gdx734slQhDCn6MWgCq3FpeqkPNNE0Xd_kHpSzcz9WCjOesHXF2wWhrRHOpBznWgj5qKAdL2wR6agWO_Lhy2IfivMsrY7suLKNmk1EnBOM2p6QkmG2hkp2o3oVzKJMahbRw3BgoKfh6bjWmrg2XG8DwKNEHqJXFpTkscxmgdh4C1ULT_RQOxR3L_43HAAc8Jr72AI9M9q7Yssh_nw_HA7NUXQvOeoOFM9LALZYtEK9v2eOhkLJIuBj9d7KjZ56VKnGWCvzoGFUphxLw_w1gET_LsX6iCJqe7lR6KnxkIwWyT2ZnBHeSwaYmGtspJhfwJuSV_sfi_cCgPjHHqcOslUaKMEfUus2gcw8q7_ieyVVYZA72LJfFWRTs_w3WQ4rFYEgsu8XX5w4FHZcN8FwwU0rvy0xe9Rlxv70t3FJOeJb68tUmRHrYB88-_UnwtoXoeu-6hi6BwJJycdza1L_EDm00)
How to use:
```java
SmartlingAuthApi authApi = new SmartlingAuthApi(userId, userSecret);
// or if you have only access_token
// SmartlingAuthApi authApi = new SmartlingAuthApi(accessToken);
FileApi fileApi = FileApi(authApi);
fileApi.deleteFile(projectId, fileUri);
```
Responsibility:
* `SmartlingAuthApi` - get `access_token` and refresh it automatically when it's expired or auth error is received
* `FileApi` - Build requests to File API and handle resposes. Uses `access_token` and proxy settings from `SmartlingAuthApi`

**Comment by dlyash** [comment]
#### Authentication and Client's API
I totally agree that the algorithm of obtaining and storing an authentication token must be replaceable. I.e. I want to be able use any of the following
  - OAuth flow
  - existing token
  - any other approach

After this is done, current `SmartlingApiManager` will have method like this:
```
    public void deleteFile(String fileUri) throws SmartlingApiException
    {
        String token = authenticationStrategy.getToken()
        fileApiClient.deleteFile(token, fileUri, connectionConfig);
    }
```

In this case, it makes sense to get rig of this facade.

#### Fluent API
Finally, I would like to have the API like following:
```
// Client using default URL no proxy and OAuth flow with caching.
import static com.smartling.sdk.auth.AuthenticationHelpers.oAuth;
...
FileApiClient client = FileApiClient.newDefaultClient()
                                    .authenticatedUsing(oAuth(userId, userSecret))
                                    .build();

// Client using specified URL
FileApiClient client = FileApiClient.newClient(customApiUrl)
                                    .authenticatedUsing(oAuth(userId, userSecret))
                                    .build();
// Client with Proxy
FileApiClient client = FileApiClient.newDefaultClient()
                                    .authenticatedUsing(oAuth(userId, userSecret))
                                    .withProxy(...)
                                    .build()

// Client with overridden authentication
FileApiClient client = FileApiClient.newDefaultClient()
                                    .authenticatedUsing(new MyCustomMechanism())
                                    .build();
//       + helper for existing token
import static com.smartling.sdk.auth.AuthenticationHelpers.existingToken;
...
FileApiClient client = FileApiClient.newDefaultClient()
                                    .authenticatedUsing(existingToken(myCustomToken))
                                    .build();
```

We will be able to design another APIs in the similar way and reuse code related to authentication.

#### Immutability, thread safety
Also, it would be great to have clients immutable. This will guarantee thread safety as long as authentication strategy is thread safe.

**Comment by dlyash** [comment]
#### Network Proxy
We has a lot of headaches related to proxying. The client for `v1` picks up proxy configuration by default if it's configured via https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html.
I believe we should stick to this behaviour. @dimitrystd ?

**Comment by dimitrystd** [comment]
I like example above. But not sure about thread statement. We should not take this responsibility and declare it.
Poxing - we definitely must provide full support here.

**Comment by paulpdaniels** [comment]
To me it would be preferable to switch to using the Apache Async Client. I'm not a fan of the current blocking model. https://hc.apache.org/httpcomponents-asyncclient-dev/quickstart.html

**Comment by dimitrystd** [comment]
Task looks like done but i didn't find
>- Request new token in case of expiration or 401
>- /example/SmartlingApiExample.java is updated
