### ISSUE TITLE
SDK v2 fails if JSON response contains more fields than expected

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-java#25]
Recently FAPI extended responses of 2 api calls (new properties were added):
* Get files list
* Get file status

Unfortunately SDK fails on json mapping because it cannot find appropriate properties in DTO object. This bug makes SDK is not backward compatible (json response was extended properly). It means SDK consumers will stop to work when FAPI will be extended.

**DoD**: SDK doesn't fail if FAPI returns json response with more fields than expected

**Comment by Hustred** [comment]
Not reprodusable
