### ISSUE TITLE
Create snippets of SDK usage for documentation team

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-java#28]
We update documentation on http://docs.smartling.com/pages/API/FileAPI/ and need new examples of SDK usage for documentation team. Previously we used `curl` and `ruby`, but since this release ruby SDK becomes obsolete and we need another examples. Java SDK is most popular so make sense to use it for examples.

**DoD**:
* Create snippet of code for each SDK method
* Techwriter should be able to paste each snippet without any additional changes. So snippet contains really everything required for demonstrate method usage

You can send him snippets as single or different plain text files.

**Comment by Hustred** [comment]
[snippets.txt](https://github.com/Smartling/api-sdk-java/files/69815/snippets.txt)
