### ISSUE TITLE
Releases missing from Maven

### ISSUE THREAD

**Issue by jhansche** [Smartling/api-sdk-java#46]
According to https://github.com/Smartling/api-sdk-java/releases there have been 4.0.18, .19, and .20 releases made.  But none of those exist in Maven central or jcenter:
https://mvnrepository.com/artifact/com.smartling/smartling-api-sdk
https://bintray.com/bintray/jcenter/com.smartling%3Asmartling-api-sdk

Additionally, if/when PR #45 is merged, it would be helpful if you can deploy that release as well.

**Comment by jhansche** [comment]
@PavloMyrotiuk I saw that the version was updated to 4.0.21, but I don't see it tagged in releases. Is there any timeline for when these versions will be released to maven central or jcenter?

**Comment by jhansche** [comment]
I see it was tagged and released to maven central today.  Thanks!

**Comment by PavloMyrotiuk** [comment]
yes, somehow took a little bit more time than usual, to sync with maven cental
