### ISSUE TITLE
Support for /project/locale/list (GET)

### ISSUE THREAD

**Issue by barlevalon** [Smartling/api-sdk-java#5]
Would be nice to have support for Projects API too.
https://docs.smartling.com/display/docs/Projects+API

**Comment by bioball** [comment]
Hi all, any chance this can get added soon?

**Comment by dimitrystd** [comment]
Hi @bioball,
Actually this task is obsolete and i'm going to close it as "won't fix". Smartling released multiple additional APIs in addition to File API. And new approach to have standalone SDK for every API (Projects; Jobs; etc). So we are not going to extend the current File API SDK with Projects API.
We still evaluate a need of other SDKs and will make them public one by one in case of demand.

**Comment by bioball** [comment]
Got it. Is the projects API available in another public java SDK?

**Comment by dimitrystd** [comment]
No for now.
